name: Beautiful Jekyll CI
on: [push, pull_request]
jobs:
  build:
    name: Build Jekyll
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the site in a ruby container
        run: |
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll \
          -e PAGES_REPO_NWO=${{ github.repository }} \
          ruby:3.1-slim /bin/bash -c "
            apt-get update -qq &&
            apt-get install -y -qq build-essential git > /dev/null 2>&1 &&
            cd /srv/jekyll &&
            rm -f Gemfile.lock &&
            bundle install --quiet &&
            bundle exec jekyll build --future
          "
